 
version: "3.7"
services:
  webserver:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DOCKER=1
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_HOST=localhost
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./docker-compose/apache2/vhost.conf:/etc/apache2/sites-available/000-default.conf